#!/usr/bin/env bash
# =============================================================================
# Generate fresh wallets for the bot and write them to .env
# Safe to re-run — will NOT overwrite an existing .env
# =============================================================================
set -euo pipefail

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
ENV_FILE="$REPO_DIR/.env"
WALLET_COUNT=5

export PATH="$HOME/.foundry/bin:$PATH"

if [ -f "$ENV_FILE" ]; then
  echo "  .env already exists — skipping wallet generation."
  echo "  Delete $ENV_FILE and re-run if you want fresh wallets."
  exit 0
fi

if ! command -v cast &>/dev/null; then
  echo "ERROR: cast (Foundry) not found. Run setup.sh first."
  exit 1
fi

echo ""
echo "Generating $WALLET_COUNT fresh wallets on Base..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Write .env header
cat > "$ENV_FILE" <<'ENVHEADER'
# JetVoy Market Bot — Wallet Configuration
# Generated by generate-wallets.sh
# NEVER share or commit this file
ENVHEADER

ADDRESSES=()

for i in $(seq 0 $((WALLET_COUNT - 1))); do
  OUTPUT=$(cast wallet new 2>&1)
  ADDRESS=$(echo "$OUTPUT" | grep "Address:" | awk '{print $2}')
  PRIVKEY=$(echo "$OUTPUT" | grep "Private key:" | awk '{print $3}')

  echo "  Wallet $i → $ADDRESS"
  echo "WALLET_KEY_$i=$PRIVKEY" >> "$ENV_FILE"
  ADDRESSES+=("$ADDRESS")
done

chmod 600 "$ENV_FILE"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Send funds to ALL of these addresses on Base:              ║"
echo "║  (ETH for gas + USDC or WETH for trading)                   ║"
echo "╠══════════════════════════════════════════════════════════════╣"
for addr in "${ADDRESSES[@]}"; do
  printf "║  %-60s ║\n" "$addr"
done
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  .env written to: $ENV_FILE"
echo "  Permissions set to 600 (owner-read only)"
echo ""
